VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True



'Private Sub Workbook_SheetDeactivate(ByVal Sh As Object)
'Application.Run "PERSONAL.XLSB!Show_Bars"
'End Sub

'Private Sub Workbook_WindowDeactivate(ByVal Wn As Window)
'Application.Run "PERSONAL.XLSB!Show_Bars"
'End Sub


